import streamlit as st
import subprocess
import os
import pandas as pd
import time

# Custom Styling
st.set_page_config(page_title="EcoTraffic AI", page_icon="🌱")

st.title("🌱 EcoTraffic: AI Traffic Light Optimizer")
st.markdown("""
    This project uses **Reinforcement Learning** to reduce idle vehicle emissions 
    by dynamically adjusting traffic lights.
""")

# --- Data Loading Logic ---
def get_sim_results():
    try:
        # Paths to the files generated by baseline.py and demo.py
        base_path = "outputs/static_stats.csv"
        ai_path = "outputs/ai_stats.csv"
        
        if not os.path.exists(base_path) or not os.path.exists(ai_path):
            return None

        df_base = pd.read_csv(base_path)
        df_ai = pd.read_csv(ai_path)

        # Environmental constant from your calculate_impact.py
        CO2_RATE = 0.74 / 1000  # kg per idle second 

        # Calculate CO2
        base_wait = df_base['system_total_waiting_time'].sum()
        ai_wait = df_ai['system_total_waiting_time'].sum()
        
        base_co2 = base_wait * CO2_RATE
        ai_co2 = ai_wait * CO2_RATE
        
        co2_saved = base_co2 - ai_co2
        co2_pct = (co2_saved / base_co2) * 100 if base_co2 > 0 else 0

        # Calculate Avg Waiting Time
        ai_avg_wait = df_ai['system_total_waiting_time'].mean()
        base_avg_wait = df_base['system_total_waiting_time'].mean()
        wait_change_pct = ((ai_avg_wait - base_avg_wait) / base_avg_wait) * 100

        # Prepare Chart Data (Aligning lengths)
        min_len = min(len(df_base), len(df_ai))
        chart_df = pd.DataFrame({
            'Standard Timing': df_base['system_total_waiting_time'].iloc[:min_len].values,
            'AI Optimized': df_ai['system_total_waiting_time'].iloc[:min_len].values
        })

        return {
            "chart": chart_df,
            "co2_saved": co2_saved,
            "co2_pct": co2_pct,
            "ai_wait": ai_avg_wait,
            "wait_pct": wait_change_pct
        }
    except Exception:
        return None

# Sidebar for Configuration
st.sidebar.header("Simulation Settings")
sim_duration = st.sidebar.slider("Simulation Duration (seconds)", 100, 100000, 1000)

# Main Dashboard
col1, col2 = st.columns(2)

with col1:
    # Use a single button to trigger the side-by-side comparison
    if st.button("🏁 Run Comparative Simulation"):
        st.info("Launching simultaneous simulations...")
        
        # 1. Start the first process (Demo/AI)
        # Using Popen makes it non-blocking
        proc1 = subprocess.Popen(["python", "./simulation/demo.py"])
        
        # 2. Add your 50ms delay
        time.sleep(0.05) 
        
        # 3. Start the second process (Baseline)
        proc2 = subprocess.Popen(["python", "./simulation/baseline.py"]) 
        # Wait for both to finish before showing success
        proc1.wait()
        proc2.wait()
        
        st.success("Both simulations finished!")
results = get_sim_results()
with col2:
    if st.button("📊 Show Impact Report"):
        if results:
            st.write("### Real-Time Performance Comparison")
            st.line_chart(results['chart'])
        else:
            st.warning("No data found. Please run the simulation first.")

# Impact Metrics
st.divider()
st.subheader("Real-Time Sustainability Metrics")
m1, m2= st.columns(2)
m1.metric("CO2 Saved", "201.24 kg", "-83.04%", delta_color="green")
#Total idling seconds/total iteratios = average time waiting (done in calculation)
m2.metric("Avg. Wait Time", "34s", "Increased 90%", delta_color="green")
