import pandas as pd

# 1. Define our environmental constants
CO2_GRAMS_PER_IDLE_SECOND = 0.74

def calculate_emissions(csv_filepath):
    """Reads the SUMO-RL output and calculates total CO2 from idling."""
    try:
        # Load the stats generated by the simulation
        df = pd.read_csv(csv_filepath)
        
        # SUMO-RL typically outputs 'system_total_waiting_time' per step
        # We sum this up to get the total seconds vehicles spent idling
        total_idle_seconds = df['system_total_waiting_time'].sum()
        
        # Convert idle time to carbon emissions
        total_co2_grams = total_idle_seconds * CO2_GRAMS_PER_IDLE_SECOND
        total_co2_kg = total_co2_grams / 1000
        
        return total_idle_seconds, total_co2_kg
    except FileNotFoundError:
        print(f"Error: Could not find {csv_filepath}. Did you run the simulation?")
        return 0, 0

# 2. Calculate for both the Baseline (Static) and the AI (Dynamic)
print("--- Sustainability Impact Report ---")

static_idle, static_co2 = calculate_emissions("../outputs/static_stats.csv")
print(f"Baseline (Static Lights): {static_co2:.2f} kg of CO2 emitted ({static_idle} seconds idling)")

ai_idle, ai_co2 = calculate_emissions("../outputs/ai_stats.csv")
print(f"AI Optimizer (Dynamic):   {ai_co2:.2f} kg of CO2 emitted ({ai_idle} seconds idling)")

# 3. Calculate the Savings!
if static_co2 > 0:
    co2_saved = static_co2 - ai_co2
    percent_reduction = (co2_saved / static_co2) * 100
    
    print("-" * 34)
    print(f"Total CO2 Prevented:      {co2_saved:.2f} kg")
    print(f"Emissions Reduction:      {percent_reduction:.1f}% decrease in carbon footprint!")